@HostAddress = http://gamestore-api-aspireapphost.dev.localhost:5159

GET {{HostAddress}}/games

###
GET {{HostAddress}}/games/1

###
POST {{HostAddress}}/games
Content-Type: application/json

{
    "name": "TEST GAME",
    "genreId": 1,
    "price": 9.99,
    "releaseDate": "1991-02-01"
}

###
PUT {{HostAddress}}/games/2
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "1991-02-01"
}

###
DELETE {{HostAddress}}/games/3

###
GET {{HostAddress}}/alive

###
GET {{HostAddress}}/health

