<Project Sdk="Aspire.AppHost.Sdk/13.3.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>70efca31-ea1d-43ac-941c-663f1ff60133</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.1" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameStore.Api\GameStore.Api.csproj" />
  </ItemGroup>

</Project>
